import AppProvider from "@/providers";
import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import "./globals.css";

const font = DM_Mono({ subsets: ["latin"], weight: ["300", "400", "500"] });

export const metadata: Metadata = {
  title: {
    default: "Epsilon",
    template: "%s | Epsilon",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <AppProvider>
          <NextTopLoader color="#C4CCCC" height={3} easing="ease" />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
